<a href="https://colab.research.google.com/github/LeedusS/python_lab/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 66015170 ชื่อ : นาย อิสรา ทองคำ

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [1]:
def leap_year(year):
    if year % 100 != 0 and year % 4 == 0:
        return True
    elif year % 400 == 0:
        return True
    else:
       return False

def day_of_year(day, month, year):
    sum_month = 0
    if leap_year(year) == True:
        days_in_month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

    if leap_year(year) == False:
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [2]:
def leap_year(year):
    if year % 100 != 0 and year % 4 == 0 and year % 400 == 0:
        return True
    else:
       return False

def day_of_year(day, month, year):
    sum_month = 1
    if leap_year(year) == True:
        days_in_month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

    if leap_year(year) == False:
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    d1,m1,y1 = date1.split("-")
    d2,m2,y2 = date2.split("-")
    d1,m1,y1 = int(d1),int(m1),int(y1)
    d2,m2,y2 = int(d2),int(m2),int(y2)
    num1 = day_in_year(y1) - day_of_year(d1, m1, y1) + 2
    num2 = day_of_year(d2, m2, y2)
    if y2 - y1 > 1:
        count = 0
        count_for = y2 - y1
        for i in range(count_for):
            if i == 0:
                continue
            count += day_in_year(y1 + i)
        return(num1 + num2  + count)-1

    if y1 == y2:
        return num1
    else:
        return(num1 + num2)

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 367 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


731
76
367
367
367
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
def leap_year(year):
    if year % 100 != 0 and year % 4 == 0 and year % 400 == 0:
        return True
    else:
       return False

def day_of_year(day, month, year):
    sum_month = 1
    if leap_year(year) == True:
        days_in_month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

    if leap_year(year) == False:
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    try:
        d1,m1,y1 = date1.split("-")
        d2,m2,y2 = date2.split("-")
        d1,m1,y1 = int(d1),int(m1),int(y1)
        d2,m2,y2 = int(d2),int(m2),int(y2)
    except ValueError:
        return -1
    num1 = day_in_year(y1) - day_of_year(d1, m1, y1) + 2
    num2 = day_of_year(d2, m2, y2)
    if (m1 or m2) > 12:
        return(-1)
    if (d1 or d2) == 31 and (m1 or m2) == (4 or 6 and 9 and 11):
        return(-1)

    if day_in_year(y1 or y2):
        if d1 == 29 and m1 == 2:
            return(-1)

    if y2 - y1 > 1:
        count = 0
        count_for = y2 - y1
        for i in range(count_for):
            if i == 0:
                continue
            count += day_in_year(y1 + i)
        return(num1 + num2  + count)-1

    if y1 == y2:
        return num1
    else:
        return(num1 + num2)

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 367 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
def simulate_fish_population(n, p, month = 40):
    DEADTIME = 5 * 12
    fish_count_history = []
    month_count = 0
    egg_fish = 0
    baby_fish = 0
    adult_fish = 0

    n = n

    for month in range(1, month + 1):
        if month_count >= DEADTIME and fish_count_history:
            n -= fish_count_history.pop(0)
        egg_fish = (n / 2) * 300
        fish_count_history.append(n)
        baby_fish += egg_fish * (1 - p / 100)
        egg_fish -= (n / 2) * 300
        adult_fish = baby_fish * (1 - p / 100)
        display_month = month * 3
        if display_month % 3 == 0:
            print(f'เดือนที่ {display_month} : ไข่ปลา : {int(egg_fish + (n / 2) * 300)} ใบ  ลูกปลา : {int(baby_fish)} ตัว  ปลาเต็มวัย : {int(adult_fish)} ตัว  รวมทั้งหมด : {int(baby_fish + adult_fish + n)} ตัว')

        adult_fish += n
        n = adult_fish

        fish_count_history.append(n)

        month_count += 1

    return egg_fish, baby_fish, adult_fish

month = 40
n = 2
p = 10

egg_fish, baby_fish, adult_fish = simulate_fish_population(n, p, month)


2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [3]:
def find_mismatch(str1, str2):
    i,j = 0,0
    count = 1
    str1, str2 = str1.lower(), str2.lower()

    if str1 == str2:
        return 0
    elif abs(len(str1) - len(str2)) >= 2:
        return 2

    while (i < len(str1)) and (j < len(str2)):

        if str1[i] != str2[j]:

            if count == 0:
                return 2
            else:
                count -= 1

            if len(str1) > len(str2):
                i += 1
            elif len(str1) < len(str2):
                j += 1
            else:
                i += 1
                j += 1
        else:
            i += 1
            j += 1
    return 1

print(find_mismatch("Python", "Java"))
print(find_mismatch("book", "boot"))
print(find_mismatch("fan", "fun"))
print(find_mismatch("sin", "sink"))
print(find_mismatch("Dog", "dog"))
print(find_mismatch("poke", "spoke"))
print(find_mismatch("poker", "poke"))


2
1
1
1
0
1
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [ ]:
def find_mismatch(str1, str2):
    i,j = 0,0
    count = 1
    str1, str2 = str1.lower(), str2.lower()

    if str1 == str2:
        return 0
    elif abs(len(str1) - len(str2)) >= 2:
        return 2

    while (i < len(str1)) and (j < len(str2)):

        if str1[i] != str2[j]:

            if count == 0:
                return 2
            else:
                count -= 1

            if len(str1) > len(str2):
                i += 1
            elif len(str1) < len(str2):
                j += 1
            else:
                i += 1
                j += 1
        else:
            i += 1
            j += 1
    return 1

def spelling_correction(input_string, correct_spells):
    output = ""
    words = input_string.split()

    for word in words:
        if len(word) <= 2:
            output += word + " "
        else:
            _min = 3
            most_similar_word = ""
            for e in correct_spells:
                result = find_mismatch(word, e)
                if result < _min:
                    _min = result
                    most_similar_word = e
            if _min == 1:
                output += most_similar_word.lower() + " "
            else:
                output += word.lower() + " "

    return output[:-1]

correct_spells = ["that", "first", "case", "car"]
input_string = "Thes is the Firs cas"
output_string = spelling_correction(input_string, correct_spells)
print(output_string)

# correct_spells = ["we", "live", "ln", "Python"]
# input_string = "Wee lpve Pythen"
# output_string = spelling_correction(input_string, correct_spells)
# print(output_string)


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
def find_word_horizontal(crosswords, word):
    for index, row in enumerate(crosswords):
        str_row = ''.join(row)
        if word in str_row:
            new_word = str_row.index(word)
            return [index , new_word]
    return None

crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
word = 'cat'
print(find_word_horizontal(crosswords, word))

5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
def find_word_vertical(crosswords,word):
    for index , col in enumerate(zip(*crosswords)):
        str_col = ''.join(col)
        if word in str_col:
            new_word = str_col.index(word)
            return[new_word,index]
    return None
crosswords = [['s','d','o','g'],
             ['c','u','c','m'],
             ['a','c','a','t'],
             ['t',' e','t','k']]
word='cat'
print(find_word_vertical(crosswords,word))


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [4]:
def find_word_vertical(crosswords,word):
    for index , col in enumerate(zip(*crosswords)):
        str_col = ''.join(col)
        if word in str_col:
            new_word = str_col.index(word)
            return[new_word,index]
    return None

def find_word_horizontal(crosswords, word):

    for index, row in enumerate(crosswords):
        str_row = ''.join(row)
        if word in str_row:
            new_word = str_row.index(word)
            return [index , new_word]
    return None

def capitalize_word_in_crossword(crosswords,word):
    vertical = find_word_vertical(crosswords,word)
    horizontal = find_word_horizontal(crosswords,word)
    if (vertical is None) and (horizontal is None) :
        return crosswords
    if (vertical is not None) and (horizontal is not None):
        vertical = None

    modi_output = [row[:] for row in crosswords]

    if (vertical is not None) :
        row_idx , col_idx = vertical
        for i in range(len(word)):
            modi_output[row_idx+i][col_idx] = modi_output[row_idx+i][col_idx].upper()
    if (horizontal is not None):
        row_idx,col_idx= horizontal
        for i in range(len(word)):
            modi_output[row_idx][col_idx+i] = modi_output[row_idx][col_idx+i].upper()

    return modi_output

crosswords=[['s','d','o','g'],['c','u','c','m'],['a','c','a','t'],['t','e','t','k']]
word='cat'

for row in capitalize_word_in_crossword(crosswords,word):
  print(row)


['s', 'd', 'o', 'g']
['c', 'u', 'c', 'm']
['a', 'C', 'A', 'T']
['t', 'e', 't', 'k']
